version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "SHA256:N14dawQw0mkucf+EuKqi98Z124GNapu4gc+yKHkaR9M"
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image
          command: |
            dd=`git log | grep Date | head -n 2 | awk 'END{printf ("%s %d, %d",$3,$4,$6)}'`
            IMAGE_TAG=`date -d $dd +"%y.%m.%d"`
            TAG_SHORT=`date -d $dd +"%y.%m"`
            echo $IMAGE_TAG
            echo $TAG_SHORT
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME
            docker push ${IMAGE_NAME}:${IMAGE_TAG}
            docker push ${IMAGE_NAME}:${TAG_SHORT}
      - run:
          name: Deploy
          command: |
            ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
            ssh $USER@$HOST < deploy.sh
            curl -L https://uich.cc/notify | bash