version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "SHA256:N14dawQw0mkucf+EuKqi98Z124GNapu4gc+yKHkaR9M"
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME
            docker tag $IMAGE_NAME ${IMAGE_NAME}:$(date -d "$(git log | grep Date | head -n 2 | awk 'END{printf ("%s %d, %d",$3,$4,$6)}')" +"%y.%m.%d")
            docker tag $IMAGE_NAME ${IMAGE_NAME}:$(date -d "$(git log | grep Date | head -n 2 | awk 'END{printf ("%s %d, %d",$3,$4,$6)}')" +"%y.%m")
            docker push ${IMAGE_NAME}:$(date -d "$(git log | grep Date | head -n 2 | awk 'END{printf ("%s %d, %d",$3,$4,$6)}')" +"%y.%m.%d")
            docker push ${IMAGE_NAME}:$(date -d "$(git log | grep Date | head -n 2 | awk 'END{printf ("%s %d, %d",$3,$4,$6)}')" +"%y.%m")
      - run:
          name: Deploy
          command: |
            ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
            ssh $USER@$HOST < deploy.sh
            curl -L https://uich.cc/notify | bash